name: Notify

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - cloud-native-toolkit/ibm-garage-iteration-zero
          - cloud-native-toolkit/automation-modules

    steps:
      - name: Repository dispatch ${{ matrix.repo }}
        uses: cloud-native-toolkit/action-repository-dispatch@main
        with:
          notifyRepo: ${{ matrix.repo }}
          eventType: released
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
