name: Verify

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_call

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verifyMetadata:
    runs-on: ubuntu-latest

    env:
      DIST_DIR: ./dist
      PUBLISH_BRANCH: gh-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: cloud-native-toolkit/action-module-metadata-create@v1
        with:
          strict: true
          validate: true
